name: Build & Test
# run-name: operation requested by ${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  scalatest:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Gensort
        run: bash script/get-gensort.sh
      - name: Setup Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: sbt
      - name: Build
        run: sbt compile
      - name: Unit tests
        run: sbt test
      - name: Assemble master module
        run: sbt "master/assembly"
      - name: Assemble worker module
        run: sbt "worker/assembly"
      - name: Correctness tests
        run: python3 script/github-action/check_correctness.py
